Lab13/Models/Persona.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab13.Models
{
    public class Persona
    {
        public int PersonaID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public DateTime FechaNac { get; set; }
        public string Direccion { get; set; }
        public string Email { get; set; }
    }
}

Lab13/Controllers/PersonaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab13.Models;

namespace Lab13.Controllers
{
    public class PersonaController : Controller
    {

        // GET: Persona
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Listar(string buscarpor, string buscar)
        {
            List<Persona> personas = new List<Persona>();
            personas.Add(new Persona
            {
                PersonaID = 1,
                Nombre = "Juan",
                Apellido = "Perez",
                Direccion = "Av. Evergreen 123",
                FechaNac = Convert.ToDateTime("1997-11-07"),
                Email = "juan@mail.com"
            });
            personas.Add(new Persona
            {
                PersonaID = 2,
                Nombre = "Maria",
                Apellido = "Salas",
                Direccion = "Av. Progreso 325",
                FechaNac = Convert.ToDateTime("1995-10-28"),
                Email = "maria@mail.com"
            });

            if (buscarpor == "Nombre")
            {
                return View(personas.Where(x => x.Nombre.StartsWith(buscar) || buscar == null).ToList());
            }
            else if (buscarpor == "Apellido")
            {
                return View(personas.Where(x => x.Apellido.StartsWith(buscar) || buscar == null).ToList());
            }
            else
            {
                return View(personas);
            }

            //return View(personas);
        }

        public ActionResult Mostrar(int id)
        {
            List<Persona> personas = new List<Persona>();
            personas.Add(new Persona
            {
                PersonaID = 1,
                Nombre = "Juan",
                Apellido = "Perez",
                Direccion = "Av. Evergen 123",
                FechaNac = Convert.ToDateTime("1997-11-07"),
                Email = "juan@mail.com"
            });

            personas.Add(new Persona
            {
                PersonaID = 2,
                Nombre = "María",
                Apellido = "Salas",
                Direccion = "Av. Progreso 325",
                FechaNac = Convert.ToDateTime("1995-10-28"),
                Email = "maria@mail.com"
            });

            personas.Add(new Persona
            {
                PersonaID = 3,
                Nombre = "Carlos",
                Apellido = "Martinez",
                Direccion = "Av. Los manzanos 3101",
                FechaNac = Convert.ToDateTime("1982-02-14"),
                Email = "carlos@mail.com"
            });

            Persona persona = (from p in personas
                               where p.PersonaID == id
                               select p).FirstOrDefault();

            return View(persona);
        }

    }
}

Lab13/Views/Persona/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Personas</h2>
@Html.ActionLink("Listar personas", "Listar", "Personas")

Lab13/Views/Persona/Listar.cshtml
@model List<Lab13.Models.Persona>
@{
    ViewBag.Title = "Listar";

    var grid = new WebGrid(source: Model, columnNames: new[]{
            "PersonaID", "Nombre", "Apellido", "FechaNac", "Direccion", "Email"
        });
}

<p>
    @using (Html.BeginForm("Listar", "Persona", FormMethod.Get))
    {
        <b>Buscar por: </b>
        @Html.RadioButton("buscarpor", "Nombre", true) <text>Nombre</text>
        @Html.RadioButton("buscarpor", "Apellido") <text>Apellido</text>
        <br />
        @Html.TextBox("buscar") <input type="submit" value="Search" />
    }
</p>

<h2>Listado de Personas</h2>
@grid.GetHtml(tableStyle: "table table-strisped",
        columns: grid.Columns(
            grid.Column(columnName: "PersonaID", header: "PersonaID"),
            grid.Column(columnName: "Nombre", header: "Nombre"),
            grid.Column(columnName: "Apellido", header: "Apellido"),
            grid.Column(columnName: "FechaNac", header: "FechaNac"),
            grid.Column(columnName: "Direccion", header: "Dirección"),
            grid.Column(columnName: "Email", header: "Email"),
            grid.Column(header: "Acciones", format: (item) =>
                                            Html.ActionLink("Ver", "Mostrar", "Persona",
                                            new { id = item.PersonaID }, null))

            )
        )

Lab13/Views/Persona/Mostrar.cshtml
@model Lab13.Models.Persona
@{
    ViewBag.Title = "Mostrar";
}

<h2>Mostrar persona</h2>

@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-md-2">
            @Html.LabelFor(model => model.PersonaID)
        </div>
        <div class="col-md-5">
            @Html.TextBoxFor(model => model.PersonaID)
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            @Html.LabelFor(model => model.Nombre)
        </div>
        <div class="col-md-5">
            @Html.TextBoxFor(model => model.Nombre)
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            @Html.LabelFor(model => model.Apellido)
        </div>
        <div class="col-md-5">
            @Html.TextBoxFor(model => model.Apellido)
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            @Html.LabelFor(model => model.FechaNac)
        </div>
        <div class="col-md-5">
            @Html.TextBoxFor(model => model.FechaNac)
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            @Html.LabelFor(model => model.Direccion)
        </div>
        <div class="col-md-5">
            @Html.TextBoxFor(model => model.Direccion)
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="col-md-5">
            @Html.TextBoxFor(model => model.Email)
        </div>
    </div>

    @Html.ActionLink("Listar Persona", "Listar", "Persona")
}